### ISSUE TITLE
[Feat]: 目前只支持ipv4，ghcr.io没有ipv6地址。后续会更新支持ipv6吗？

### ISSUE THREAD

**Issue by LesenHuang** [wg-easy/wg-easy#1452] opened 2024-10-06 09:18 UTC
### Description

<img width="806" alt="截屏2024-10-06 下午5 14 03" src="https://github.com/user-attachments/assets/5c03ca43-3086-4434-b5ed-128aab6169bd">

### Suggested Solution

none

**Comment by kaaax0815** [comment] 2024-10-07 06:14
Please post your issues in english.

Duplicate of #138.

Will be supported when #1333 is merged

**Closed by kaaax0815** 2024-10-07 06:14 UTC
Labels: type: feature request
