### ISSUE TITLE
[Bug]: ENABLE_PROMETHEUS_METRICS=true not enabling metrics

### ISSUE THREAD

**Issue by weinix** [wg-easy/wg-easy#1537] opened 2024-11-29 04:44 UTC
### Describe the bug

# Describe the bug
`ENABLE_PROMETHEUS_METRICS=true` is set but metrics is not found. Everything else is working fine.

### Expected behavior

# Expect result 
Prometheus metrics is available

### Relevant log output

```shell
$ docker pull ghcr.io/wg-easy/wg-easy
Using default tag: latest
latest: Pulling from wg-easy/wg-easy
Digest: sha256:66352ccb4b5095992550aa567df5118a5152b6ed31be34b0a8e118a3c3a35bf5
Status: Image is up to date for ghcr.io/wg-easy/wg-easy:latest
ghcr.io/wg-easy/wg-easy:latest

# start the service 
$ docker exec -it wg-easy-admin-1 bash
wg-easy-admin:/app/www# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
2: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.8.0.1/24 scope global wg0
       valid_lft forever preferred_lft forever
145: eth0@if146: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.3/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
wg-easy-admin:/app/www# curl 172.17.0.3:51821/metrics
{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}wg-easy-admin:/app/www# curl 127.0.0.1:51821/metrics
{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}
```

**Comment by moppman** [comment] 2024-11-29 17:41
Duplicate of #1373

The `:latest` image is built against the `production` branch, which means the metrics endpoint is not available there.

**Comment by weinix** [comment] 2024-12-01 06:28
thank you, @moppman !

**Comment by therus000** [comment] 2024-12-02 12:05
i got same problem

**Comment by moppman** [comment] 2024-12-02 12:56
> i got same problem { "statusCode": 404, "statusMessage": "Cannot find static asset /metrics", "stack": [] }

[Like I said ](https://github.com/wg-easy/wg-easy/issues/1537#issuecomment-2508200315), the metrics endpoint is not avaible in the `:latest` Docker image, which currently maps to `v14`.
That means you can either wait for the release of `v15` or you can switch to the [`:nightly`](https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy/314984618?tag=nightly) image, which obviously isn't stable.

**Comment by Ayo91** [comment] 2024-12-03 13:28
Is it working for anyone? Im running it inside a proxmox lxc and I see this error on Grafana:
![Image](https://github.com/user-attachments/assets/1d5d2724-5489-433b-adf0-fa264af108dc)


When I open it on a browser seems reachable:
![Image](https://github.com/user-attachments/assets/3f34b6bb-85ee-4442-9faf-3e3a934039f7)

How can I get more details what is failing

Both containers are in the same network and subnet

**Comment by moppman** [comment] 2024-12-03 15:05
@Ayo91 
What version of wg-easy are you running? Like I said earlier, version <= `v14` don't support Prometheus metrics.

**Comment by Ayo91** [comment] 2024-12-03 15:08
> [@Ayo91](https://github.com/Ayo91) What version of wg-easy are you running? Like I said earlier, version <= `v14` don't support Prometheus metrics.

nightly version, you see that the endpoint exists

**Comment by Festival0103** [comment] 2024-12-05 14:05
I have the same error, as @Ayo91.  Nightly version, http://x.x.x.x:51821/metrics as datasource URL. With or without authentification.

**Comment by Ayo91** [comment] 2024-12-05 15:42
> I have the same error, as [@Ayo91](https://github.com/Ayo91). Nightly version, http://x.x.x.x:51821/metrics as datasource URL. With or without authentification.

I have exactly that...http://192.168.1.203:51821/metrics

**Comment by kaaax0815** [comment] 2024-12-09 08:13
Closing
Ref: https://github.com/wg-easy/wg-easy/issues/1537#issuecomment-2508200315

**Closed by kaaax0815** 2024-12-09 08:13 UTC
Labels: type: bug
