### ISSUE TITLE
Endless loading of the client list after last update in web.

### ISSUE THREAD

**Issue by Justieku** [wg-easy/wg-easy#1272] opened 2024-08-12 08:52 UTC
**Describe the bug**
Endless loading of the client list after last update in web. Vpn is working but I cannot see and add new clients.

docker stop wg-easy
docker rm wg-easy
docker pull ghcr.io/wg-easy/wg-easy

  docker run -d \
  --name=wg-easy \
  -e LANG=de \
  -e WG_HOST=MY IP HERE \
  -e PASSWORD_HASH='$2a$12$8pVc57k2p1LL9eSPnhMY PASSWORD HASHpj2caE8gHsKwKhgk8HPSm' \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy

**Expected behavior**
After update vpn is working great! but I cannot see list of clients now and add new ones.

**Screenshots**
![image](https://github.com/user-attachments/assets/744f5bfb-640b-4999-9c66-0e3dc763eb81)
![image](https://github.com/user-attachments/assets/1bb79cce-131e-4681-9a3f-e4ddfb1c6551)

**Desktop (please complete the following information):**
 - OS: linux ubuntu server 24.01
 - Browser [chrome]

**Additional context**

**Comment by eandersons** [comment] 2024-08-12 09:07
If you have not seen it, GitHub has a cool feature - search. You should use it before adding new issues to see if the same issue has not been already reported. Try it: [endless](/wg-easy/wg-easy/issues?q=is%3Aissue+endless+).

This is a duplicate of #1263.

**Comment by Justieku** [comment] 2024-08-12 09:31
> If you have not seen it, GitHub has a cool feature - search. You should use it before adding new issues to see if the same issue has not been already reported. Try it: [endless](/wg-easy/wg-easy/issues?q=is%3Aissue+endless+).
> 
> This is a duplicate of #1263.

Yes, sorry. I will delete this issue. Many thanks

**Closed** 2024-08-23 05:36 UTC
