### ISSUE TITLE
Unable to start WG-easy using v8

### ISSUE THREAD

**Issue by rusty1281** [wg-easy/wg-easy#682] opened 2023-12-20 01:02 UTC
**Describe the bug**
When using the latest docker image from ghcr.io/wg-easy/wg-easy I am unable to get the container going. Results with the following issue:

```
2023-12-19T20:12:12.563Z Server Listening on http://0.0.0.0:51821
2023-12-19T20:12:12.565Z WireGuard Loading configuration...
2023-12-19T20:12:12.569Z WireGuard Configuration loaded.
2023-12-19T20:12:12.569Z WireGuard Config saving...
2023-12-19T20:12:12.571Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#]
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
[#] ip link delete dev wg0
at ChildProcess.exithandler (node:child_process:422:12)
at ChildProcess.emit (node:events:517:28)
at maybeClose (node:internal/child_process:1098:16)
at Socket.<anonymous> (node:internal/child_process:450:11)
at Socket.emit (node:events:517:28)
at Pipe.<anonymous> (node:net:350:12) {
code: 4,
killed: false,
signal: null,
cmd: 'wg-quick up wg0'
}
```

**To Reproduce**
Running the latest image using the suggested docker run or compose setup

Running this on a Synology NAS that already has WG support installed and working (with older container image). Have multiple confirmations from a number of Synology models/users.

Also, manually running wg-quick up wg0 (using the same location of the wg0 file that wgeasy does), in fact successfully starts the wg-crypt-wg0 process. Ofc, running container after that reports the port is already in use. So again, with v7 of wgeasy everything is running smooth, but the latest v8 image is causing issues.

Any assistance would be appreciated. If needed I can post any log, or execute any command as needed.

Thank you in advance!

**Comment by BerserkeR-Git** [comment] 2023-12-20 03:57
I have the exact same issue. Following.

**Comment by mandre00** [comment] 2023-12-20 08:31
Same issue since yesterday

**Comment by AlimFreight** [comment] 2023-12-20 20:55
Same here, returned to previous version.

**Comment by eandersons** [comment] 2023-12-21 07:31
The key message in the container output is this: `Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?`
Searching by it brings up results that point to GitHub issues in various projects, of which one is also related to Synology NAS: https://github.com/lisenet/docker-openvpn/issues/4, which leads to a conclusion that Synology NAS is using legacy iptables.
Based on the information that can be found in the mentioned issue, the solution would be to modify [`Dockerfile`](/wg-easy/wg-easy/blob/master/Dockerfile) to replace `iptables` (it was added with 024abce7e5b1c86435211b19d6ba556f264aff30) with `iptables-legacy` and build a local image of WireGuard Easy (I did not test this approach as I do not have Synology NAS).

**Comment by peterlewis** [comment] 2023-12-21 13:07
I believe this issue has arisen since the [update to Alpine 3.19](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.19.0), for which the release notes state:

> Since the new iptables- binaries also don't use the iptables backend, to work with any existing rules and save them, you need to install [iptables-legacy](https://pkgs.alpinelinux.org/packages?name=iptables-legacy&branch=edge&repo=&arch=x86_64&maintainer=) and use iptables-legacy-save.

**Comment by peterlewis** [comment] 2023-12-21 13:11
@pheiduck It appears that this does indeed affect wg-easy on certain platforms. Shall we look to expedite the merge upstream and then we can tackle this in the project repo? Should be as simple as replacing `iptables` with `iptables-legacy` if my optimism is correct!

**Comment by rusty1281** [comment] 2023-12-21 13:21
> @pheiduck It appears that this does indeed affect wg-easy on certain platforms. Shall we look to expedite the merge upstream and then we can tackle this in the project repo? Should be as simple as replacing `iptables` with `iptables-legacy` if my optimism is correct!

That would be great! I would be open to help out and test any release (image) on multiple **synology boxes** to make sure that this platform is covered.

**Comment by pheiduck** [comment] 2023-12-21 13:31
> @pheiduck It appears that this does indeed affect wg-easy on certain platforms. Shall we look to expedite the merge upstream and then we can tackle this in the project repo? Should be as simple as replacing `iptables` with `iptables-legacy` if my optimism is correct!

Yes, as Synology is using a very old Kernel. It can help to use `iptables-legacy`.

**Comment by peterlewis** [comment] 2023-12-21 17:33
> Should be as simple as replacing `iptables` with `iptables-legacy` if my optimism is correct!

My optimism was not correct. This needs a wee bit more investigation.

**Comment by rusty1281** [comment] 2023-12-21 17:35
> > Should be as simple as replacing `iptables` with `iptables-legacy` if my optimism is correct!
> 
> My optimism was not correct. This needs a wee bit more investigation.

Was just about to ask if these changes are now part of the nightly image so I can test it. Guessing this is not then working still for this particular case?

**Comment by pheiduck** [comment] 2023-12-21 17:38
> these changes are now part of the nightly image
@rusty1281 yes, please test and give us feedback. :)

**Comment by rusty1281** [comment] 2023-12-21 17:46
> > Was just about to ask if these changes are now part of the nightly image so I can test it. Guessing this is not then working still for this particular case?
> 
> @rusty1281 yes, please test and give us feedback. :)

Unfortunately the output is the same:

```
2023-12-21T17:45:22.787Z Server Listening on http://0.0.0.0:51821
2023-12-21T17:45:22.789Z WireGuard Loading configuration...
2023-12-21T17:45:22.792Z WireGuard Configuration loaded.
2023-12-21T17:45:22.792Z WireGuard Config saving...
2023-12-21T17:45:22.794Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
[#] ip link delete dev wg0
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 4,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

**Comment by pheiduck** [comment] 2023-12-21 18:51
I think it is a kernel problem because Synology uses older kernel versions.
`Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?`

**Comment by peterlewis** [comment] 2023-12-21 19:59
@rusty1281 Can you please give `ghcr.io/wg-easy/wg-easy:development` a go and see if that fixes the issue for you? Thanks!

**Comment by LoV432** [comment] 2023-12-21 20:05
> @rusty1281 Can you please give `ghcr.io/wg-easy/wg-easy:development` a go and see if that fixes the issue for you? Thanks!

I am facing the same issue on Manjaro and i can confirm this development branch fixes the issue. (For me at least)

**Comment by AlimFreight** [comment] 2023-12-21 20:08
Yes i can confirm the development branch fixes the issue for me as well.
Alpine 3.19

**Comment by rusty1281** [comment] 2023-12-21 20:13
> @rusty1281 Can you please give `ghcr.io/wg-easy/wg-easy:development` a go and see if that fixes the issue for you? Thanks!

Tested on two separate Syno boxes and a VDSM, works like a charm. 

<img width="853" alt="Screenshot 2023-12-21 at 21 12 08" src="https://github.com/wg-easy/wg-easy/assets/5110408/c5c4b13d-5717-4386-a047-fbd2670ae574">

```
2023-12-21T20:11:37.244Z Server Listening on http://0.0.0.0:51821
2023-12-21T20:11:37.246Z WireGuard Loading configuration...
2023-12-21T20:11:37.248Z WireGuard Configuration loaded.
2023-12-21T20:11:37.248Z WireGuard Config saving...
2023-12-21T20:11:37.249Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2023-12-21T20:11:37.491Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2023-12-21T20:11:37.508Z WireGuard Config synced.
2023-12-21T20:11:53.058Z Server New Session: Qijn9UfIjvexxxxxxxxxx
```

**Comment by peterlewis** [comment] 2023-12-21 20:20
Excellent news!

**Comment by peterlewis** [comment] 2023-12-21 21:01
I'm sorry to hear that, @BerserkeR-Git. Could I ask you to raise a new issue with the above and we'll look to address it? Thank you!

**Comment by pheiduck** [comment] 2023-12-21 21:19
@BerserkeR-Git please test: ghcr.io/wg-easy/wg-easy:development

**Comment by peterlewis** [comment] 2023-12-22 07:32
Re-opening issue, just until we've got the fix for this merged into `latest`.

**Comment by peterlewis** [comment] 2023-12-22 08:28
Fix included in `latest` release (v9).

**Closed by peterlewis** 2023-12-22 08:28 UTC
Labels: bug

**Comment by rusty1281** [comment] 2023-12-22 08:53
I’m currently driving but will be home in a few hours and will test this as well and post back. 

Thank you again for your commitment to make this solution as compatible as possible.

**Comment by rusty1281** [comment] 2023-12-22 12:32
I have just tested the latest image and can report that it works fine on multiple Syno NAS boxes. Updated my production as well.

**Comment by reedone816** [comment] 2024-11-28 02:40
not working on docker on rocky linux 9.4, 
with the same culprit, iptables.

[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptable                                                                                        s -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j                                                                                         ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not                                                                                         exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
