### ISSUE TITLE
Wireguard not working in release tagged 13 (latest)

### ISSUE THREAD

**Issue by LoomeL** [wg-easy/wg-easy#1045] opened 2024-05-16 18:44 UTC
I just updated to version 13, the application works, but Wireguard does not. I rolled back to 12 and everything works again. There are no errors in the logs. I don't know what additional information there is.

**Comment by Codelica** [comment] 2024-05-16 21:39
Are you setting a custom `WG_PORT` by chance?  I was just trying out wg-easy and noticed the current image doesn't act the way the docs describe for that parameter:

> `WG_PORT:` The public UDP port of your VPN server. **WireGuard will always listen on 51820 inside the Docker container**.

Yet changing `WG_PORT` does change the `ListenPort` in `wg0.conf` and you can see it listening internally on that configured port.  Which (incorrect docs aside) is fine, except the port used in the default `PostUp` and `PostDown` config is not changed accordingly so NAT is also broken.

The only way I could get it to work with a custom port is by:

- Passing that new internal port through
- Custom `PostUp` and `PostDown` to match

Seems like a bug.

**Comment by eandersons** [comment] 2024-05-17 05:32
This is a duplicate of #1032.
Search for existing issues before posting new ones, people!

**Comment by pheiduck** [comment] 2024-05-17 09:52
Please try latest dev

**Closed** 2024-05-18 12:09 UTC
