### ISSUE TITLE
[Bug]: Why do I keep getting this error?

### ISSUE THREAD

**Issue by Pel0915** [wg-easy/wg-easy#1594] opened 2024-12-27 16:44 UTC
### Describe the bug

Error content

```shell

stderr: Error: WireGuard exited with the error: Cannot find device "wg0"
stderr: This usually means that your host's kernel does not support WireGuard!
stderr: at /app/lib/WireGuard.js:74:17
stderr: at async WireGuard.getConfig (/app/lib/WireGuard.js:72:7)
stderr: 2024-12-27T16:34:08.632Z Server Listening on http://0.0.0.0:51821
stderr: 2024-12-27T16:34:08.640Z WireGuard Loading configuration...
stderr: 2024-12-27T16:34:08.644Z WireGuard Configuration loaded.
stderr: 2024-12-27T16:34:08.645Z WireGuard Config saving...
stderr: 2024-12-27T16:34:08.648Z WireGuard Config saved.
stdout: $ wg-quick down wg0
stdout: $ wg-quick up wg0
stderr: Error: WireGuard exited with the error: Cannot find device "wg0"
stderr: This usually means that your host's kernel does not support WireGuard!
stderr: at /app/lib/WireGuard.js:74:17
stderr: at async WireGuard.getConfig (/app/lib/WireGuard.js:72:7)`

```
### Expected behavior

Work just fine!

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment] 2024-12-27 18:37
This is a duplicate of multiple closed issues
See [Cannot find device "wg0"](/wg-easy/wg-easy/issues?q=is%3Aissue+Cannot+find+device+%22wg0%22)

**Closed by kaaax0815** 2024-12-27 18:37 UTC
Labels: type: bug
