### ISSUE TITLE
[Feat]: A button to change endpoints user can access

### ISSUE THREAD

**Issue by qvipin** [wg-easy/wg-easy#1520] opened 2024-11-16 01:21 UTC
### Description

When generating a config, it would be nice to be able to change the endpoints that certain users can access if I wanted to send it to people

### Suggested Solution

Maybe a button like the other 3 buttons with a textbox where you can set allowed endpoints on the local network.

### Alternatives

My alternative solution currently is just to go into the container file system and edit the wg files in there.

**Comment by kaaax0815** [comment] 2024-11-17 00:05
Setting Allowed Ips implemented in #1333

Configuring Firewall duplicate of #1513

**Closed by kaaax0815** 2024-11-17 00:05 UTC
Labels: type: feature request

**Comment by qvipin** [comment] 2024-11-17 07:07
has it already been setup to set allowed ips

**Comment by qvipin** [comment] 2024-11-17 07:08
i see https://github.com/wg-easy/wg-easy/pull/759

**Comment by kaaax0815** [comment] 2024-11-17 09:17
Will be implemented in 15.0.0
