### ISSUE TITLE
[Bug]: Error: Command failed: wg-quick up wg0; iptables v1.8.10 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)

### ISSUE THREAD

**Issue by Asbjorn88** [wg-easy/wg-easy#1554] opened 2024-12-08 20:30 UTC
### Describe the bug

System info:

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.21.0
PRETTY_NAME="Alpine Linux v3.21"

Bash history:
```
cat /etc/sysctl.conf 
net.ipv4.ip_forward = 1
rc-update add sysctl
sysctl -p

apk add podman
rc-update add cgroups
rc-service cgroups start

apk add wireguard-tools-wg-quick
apk add iptables


###Added module
cat /etc/modules-load.d/ip_tables 
ip_tables

mkdir -p /opt/wg-easy
```

Run container:
```
podman run -d  \
--name=wg-easy \
-e PORT=62921 \
-e WG_PORT=61820 \
-e WG_HOST=162.15.62.76 \
-e PASSWORD_HASH='$2a$16$uiafk3Hg9jnBqXroUqIrjtkSC5/veUhJjlzc1gNefK4.WUH.HVc/S' \
-e WG_DEFAULT_ADDRESS=192.168.20.x \
-e WG_CONFIG_PORT=62921 \
-e WG_PERSISTENT_KEEPALIVE=25 \
-e WG_DEFAULT_DNS='192.168.20.254, 1.1.1.1' \
-e LANG=ru \
-e UI_TRAFFIC_STATS=true \
-e UI_CHART_TYPE=true \
-e WG_ENABLE_ONE_TIME_LINKS=true \
-e UI_ENABLE_SORT_CLIENTS=true \
-e ENABLE_PROMETHEUS_METRICS=true \
-v /opt/wg-easy:/etc/wireguard  \
-p 61820:61820/udp \
-p 62921:62921/tcp \
--cap-add=NET_ADMIN \
--cap-add=SYS_MODULE \
--sysctl='net.ipv4.conf.all.src_valid_mark=1' \
--sysctl='net.ipv4.ip_forward=1' \
--restart unless-stopped \
ghcr.io/wg-easy/wg-easy
```

### Expected behavior

Work just fine!

### Relevant log output

```shell
2024-12-08T20:12:26.973Z Server Listening on http://0.0.0.0:62921
2024-12-08T20:12:26.980Z WireGuard Loading configuration...
2024-12-08T20:12:26.985Z WireGuard Configuration loaded.
2024-12-08T20:12:26.986Z WireGuard Config saving...
2024-12-08T20:12:26.988Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 192.168.20.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 192.168.20.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 61820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 3,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

**Comment by kaaax0815** [comment] 2024-12-09 08:10
Duplicate of https://github.com/wg-easy/wg-easy/issues/308

**Closed by kaaax0815** 2024-12-09 08:10 UTC
Labels: type: bug

**Comment by Asbjorn88** [comment] 2024-12-09 09:09
Thanks!


you need to add the --cap-add=NET_RAW parameter

Summary:
```
podman run -d  \
--name=wg-easy \
-e PORT=62921 \
-e WG_PORT=61820 \
-e WG_HOST=162.15.62.76 \
-e PASSWORD_HASH='$2a$16$uiafk3Hg9jnBqXroUqIrjtkSC5/veUhJjlzc1gNefK4.WUH.HVc/S' \
-e WG_DEFAULT_ADDRESS=192.168.20.x \
-e WG_CONFIG_PORT=62921 \
-e WG_PERSISTENT_KEEPALIVE=25 \
-e WG_DEFAULT_DNS='192.168.20.254, 1.1.1.1' \
-e LANG=ru \
-e UI_TRAFFIC_STATS=true \
-e UI_CHART_TYPE=true \
-e WG_ENABLE_ONE_TIME_LINKS=true \
-e UI_ENABLE_SORT_CLIENTS=true \
-e ENABLE_PROMETHEUS_METRICS=true \
-v /opt/wg-easy:/etc/wireguard  \
-p 61820:61820/udp \
-p 62921:62921/tcp \
--cap-add=NET_ADMIN \
--cap-add=SYS_MODULE \
--cap-add=NET_RAW  \
--sysctl='net.ipv4.conf.all.src_valid_mark=1' \
--sysctl='net.ipv4.ip_forward=1' \
--restart unless-stopped \
ghcr.io/wg-easy/wg-easy
```
