### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Zane173** [wg-easy/wg-easy#1496] opened 2024-10-25 20:44 UTC
### Describe the bug

metrics is not showing up

### Expected behavior

{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}

### Relevant log output

{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}

**Comment by tokKurumi** [comment] 2024-10-26 19:30
Duplicate of #1373

**Closed** 2024-10-27 16:36 UTC
Labels: type: bug
