### ISSUE TITLE
[Bug]: wgpw not prompting for password if none given

### ISSUE THREAD

**Issue by kapuett** [wg-easy/wg-easy#1498] opened 2024-10-27 05:23 UTC
### Describe the bug

Docker:
```
Docker version 27.3.1, build ce12230
```
OS:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
```
wg-easy image used:
``` 
https://github.com/wg-easy/wg-easy/releases/tag/v14.0.0
```
Documentation at https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md#usage-with-docker states that if
```
docker run -it ghcr.io/wg-easy/wg-easy wgpw
```
is called (without giving a password), one will be prompted for one. That is not the case:

```
$ sudo docker run -it ghcr.io/wg-easy/wg-easy wgpw
$
[...]
sudo docker run -it ghcr.io/wg-easy/wg-easy bash
d1cdd90fb480:/app# wgpw
d1cdd90fb480:/app#
```
Giving PW works just fine:
```
❯ sudo docker run -it ghcr.io/wg-easy/wg-easy wgpw 'test'
PASSWORD_HASH='$2a$12$gdAjPD.RSJLzwH4A2pycfua/z5FHmD2jLT/ypDl/jjvgturDG2wrW'    
```
But usage should either reflect docu or lose that part in the docs.

### Expected behavior

Prompt me for a password if none is given when running `wgpw`.

### Relevant log output

❯ sudo docker run -it ghcr.io/wg-easy/wg-easy wgpw
❯

**Comment by moppman** [comment] 2024-10-27 13:59
You're running the `ghcr.io/wg-easy/wg-easy`, which defaults to `:latest`, which is the current stable version 14. 
Unfortunately, the default branch of this repo is the `master` branch, which does not represent `:latest` but does represent `:nightly`.
Getting prompted for a password in `wgpw` has been added in https://github.com/wg-easy/wg-easy/commit/11872de321159ba49b896d5de874cd062cd2dca9, which hasn't been merged into master yet.
If you switch to the production branch, you'll see that there's no mentioning of this feature in the documentation.

**Comment by kaaax0815** [comment] 2024-10-27 16:45
duplicate of https://github.com/wg-easy/wg-easy/issues/1455

**Closed by kaaax0815** 2024-10-27 16:45 UTC
Labels: type: bug

**Comment by kapuett** [comment] 2024-10-28 04:45
My bad guys, sorry for taking up your time. Seems I couldn't think straight yesterday, instead of searching for keywords of my issue I just had a look at the open ones and thus missing that it is a duplicate of an already closed one.
