### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by xtforever** [wg-easy/wg-easy#1521] opened 2024-11-16 12:01 UTC
### Describe the bug

I fetched  the provided docker-compose.yml and did a docker compose up.
the container is restarting and this is the error:

wg-easy  | iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)

### Expected behavior

Work just fine!

### Relevant log output

```shell
wg-easy  | [#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
wg-easy  | modprobe: can't change directory to '/lib/modules': No such file or directory
wg-easy  | modprobe: can't change directory to '/lib/modules': No such file or directory
wg-easy  | iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
wg-easy  | Perhaps iptables or your kernel needs to be upgraded.
wg-easy  | [#] ip link delete dev wg0
wg-easy  | 
wg-easy  |     at genericNodeError (node:internal/errors:984:15)
wg-easy  |     at wrappedFn (node:internal/errors:538:14)
wg-easy  |     at ChildProcess.exithandler (node:child_process:422:12)
wg-easy  |     at ChildProcess.emit (node:events:519:28)
wg-easy  |     at maybeClose (node:internal/child_process:1105:16)
wg-easy  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
wg-easy  |   code: 3,
wg-easy  |   killed: false,
wg-easy  |   signal: null,
wg-easy  |   cmd: 'wg-quick up wg0'
wg-easy  | }
wg-easy exited with code 1
```

**Comment by kaaax0815** [comment] 2024-11-17 14:21
Duplicate of #1217, #829

**Closed by kaaax0815** 2024-11-17 14:21 UTC
Labels: type: bug
