### ISSUE TITLE
[Bug]: Prometheus /metrics access

### ISSUE THREAD

**Issue by jkawka** [wg-easy/wg-easy#1418] opened 2024-09-19 08:37 UTC
### Describe the bug

Unfortunately but access to Prometheus doesn't work:
```
{
"statusCode": 404,
"statusMessage": "Cannot find static asset /metrics",
"stack": []
}
```

option is enabled ENABLE_PROMETHEUS_METRICS=true and password also set

### Expected behavior

display metrics at /metrics url

**Comment by kaaax0815** [comment] 2024-09-19 08:45
duplicate of #1373

**Closed by kaaax0815** 2024-09-19 08:45 UTC
Labels: type: bug, status: duplicate
