### ISSUE TITLE
[Bug]: Calculations of the date and volume consumed per user

### ISSUE THREAD

**Issue by eylandoo** [wg-easy/wg-easy#1481] opened 2024-10-18 03:04 UTC
### Describe the bug

hello
Please create an expiration date for each user in the new update. 
As well as the ability to control the volume consumed for each user 
This way I can better control the user 

### Expected behavior

Work just fine!

**Comment by kaaax0815** [comment] 2024-10-18 07:10
You can currently set an expiration data for each client in the `nightly` version.

Controlling quota (data usage) is already noted here https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297
Also duplicate of #1404

**Closed by kaaax0815** 2024-10-18 07:10 UTC
Labels: type: bug
