### ISSUE TITLE
[Bug]: Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE, USE PASSWORD_HASH INSTEAD

### ISSUE THREAD

**Issue by FlavioB79** [wg-easy/wg-easy#1366] opened 2024-09-06 16:44 UTC
### Describe the bug

After upgrading to the latest version (wg-easy:latest) my docker container, WG wouldn't work anymore and the error is as typed in the title.
I'm running on a Synology NAS.

### Expected behavior

Work just fine!

### Relevant log output

```shell
wg-easy
date	stream	content
2024/09/06 18:42:59	stderr	Node.js v20.17.0
2024/09/06 18:42:59	stderr	
2024/09/06 18:42:59	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:42:59	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:42:59	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:42:59	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:42:59	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:42:59	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:42:59	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:42:59	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:42:59	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:42:59	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:42:59	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:42:59	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:42:59	stderr	
2024/09/06 18:42:59	stderr	      ^
2024/09/06 18:42:59	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:42:59	stderr	/app/lib/Server.js:311
2024/09/06 18:41:57	stderr	Node.js v20.17.0
2024/09/06 18:41:57	stderr	
2024/09/06 18:41:57	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:41:57	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:41:57	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:41:57	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:41:57	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:41:57	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:41:57	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:41:57	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:41:57	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:41:57	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:41:57	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:41:57	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:41:57	stderr	
2024/09/06 18:41:57	stderr	      ^
2024/09/06 18:41:57	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:41:57	stderr	/app/lib/Server.js:311
2024/09/06 18:40:54	stderr	Node.js v20.17.0
2024/09/06 18:40:54	stderr	
2024/09/06 18:40:54	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:40:54	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:40:54	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:40:54	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:40:54	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:40:54	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:40:54	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:40:54	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:40:54	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:40:54	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:40:54	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:40:54	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:40:54	stderr	
2024/09/06 18:40:54	stderr	      ^
2024/09/06 18:40:54	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:40:54	stderr	/app/lib/Server.js:311
2024/09/06 18:39:52	stderr	Node.js v20.17.0
2024/09/06 18:39:52	stderr	
2024/09/06 18:39:52	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:39:52	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:39:52	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:39:52	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:39:52	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:39:52	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:39:52	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:39:52	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:39:52	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:39:52	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:39:52	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:39:52	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:39:52	stderr	
2024/09/06 18:39:52	stderr	      ^
2024/09/06 18:39:52	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:39:52	stderr	/app/lib/Server.js:311
2024/09/06 18:38:49	stderr	Node.js v20.17.0
2024/09/06 18:38:49	stderr	
2024/09/06 18:38:49	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:38:49	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:38:49	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:38:49	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:38:49	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:38:49	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:38:49	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:38:49	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:38:49	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:38:49	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:38:49	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:38:49	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:38:49	stderr	
2024/09/06 18:38:49	stderr	      ^
2024/09/06 18:38:49	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:38:49	stderr	/app/lib/Server.js:311
2024/09/06 18:37:47	stderr	Node.js v20.17.0
2024/09/06 18:37:47	stderr	
2024/09/06 18:37:47	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:37:47	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:37:47	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:37:47	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:37:47	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:37:47	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:37:47	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:37:47	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:37:47	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:37:47	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:37:47	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:37:47	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:37:47	stderr	
2024/09/06 18:37:47	stderr	      ^
2024/09/06 18:37:47	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:37:47	stderr	/app/lib/Server.js:311
2024/09/06 18:36:53	stderr	Node.js v20.17.0
2024/09/06 18:36:53	stderr	
2024/09/06 18:36:53	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:53	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:36:53	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:36:53	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:36:53	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:36:53	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:36:53	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:36:53	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:53	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:36:53	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:36:53	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:36:53	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:36:53	stderr	
2024/09/06 18:36:53	stderr	      ^
2024/09/06 18:36:53	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:36:53	stderr	/app/lib/Server.js:311
2024/09/06 18:36:25	stderr	Node.js v20.17.0
2024/09/06 18:36:25	stderr	
2024/09/06 18:36:25	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:25	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:36:25	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:36:25	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:36:25	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:36:25	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:36:25	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:36:25	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:25	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:36:25	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:36:25	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:36:25	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:36:25	stderr	
2024/09/06 18:36:25	stderr	      ^
2024/09/06 18:36:25	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:36:25	stderr	/app/lib/Server.js:311
2024/09/06 18:36:10	stderr	Node.js v20.17.0
2024/09/06 18:36:10	stderr	
2024/09/06 18:36:10	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:10	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:36:10	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:36:10	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:36:10	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:36:10	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:36:10	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:36:10	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:10	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:36:10	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:36:10	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:36:10	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:36:10	stderr	
2024/09/06 18:36:10	stderr	      ^
2024/09/06 18:36:10	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:36:10	stderr	/app/lib/Server.js:311
2024/09/06 18:36:01	stderr	Node.js v20.17.0
2024/09/06 18:36:01	stderr	
2024/09/06 18:36:01	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:01	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:36:01	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:36:01	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:36:01	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:36:01	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:36:01	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:36:01	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:36:01	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:36:01	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:36:01	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:36:01	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:36:01	stderr	
2024/09/06 18:36:01	stderr	      ^
2024/09/06 18:36:01	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:36:01	stderr	/app/lib/Server.js:311
2024/09/06 18:35:56	stderr	Node.js v20.17.0
2024/09/06 18:35:56	stderr	
2024/09/06 18:35:56	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:56	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:35:56	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:35:56	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:35:56	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:35:56	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:35:56	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:35:56	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:56	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:35:56	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:35:56	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:35:56	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:35:56	stderr	
2024/09/06 18:35:56	stderr	      ^
2024/09/06 18:35:56	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:35:56	stderr	/app/lib/Server.js:311
2024/09/06 18:35:52	stderr	Node.js v20.17.0
2024/09/06 18:35:52	stderr	
2024/09/06 18:35:52	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:52	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:35:52	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:35:52	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:35:52	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:35:52	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:35:52	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:35:52	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:52	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:35:52	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:35:52	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:35:52	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:35:52	stderr	
2024/09/06 18:35:52	stderr	      ^
2024/09/06 18:35:52	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:35:52	stderr	/app/lib/Server.js:311
2024/09/06 18:35:49	stderr	Node.js v20.17.0
2024/09/06 18:35:49	stderr	
2024/09/06 18:35:49	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:49	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:35:49	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:35:49	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:35:49	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:35:49	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:35:49	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:35:49	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:49	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:35:49	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:35:49	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:35:49	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:35:49	stderr	
2024/09/06 18:35:49	stderr	      ^
2024/09/06 18:35:49	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:35:49	stderr	/app/lib/Server.js:311
2024/09/06 18:35:43	stderr	Node.js v20.17.0
2024/09/06 18:35:43	stderr	
2024/09/06 18:35:43	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:43	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:35:43	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:35:43	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:35:43	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:35:43	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:35:43	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:35:43	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:43	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:35:43	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:35:43	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:35:43	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:35:43	stderr	
2024/09/06 18:35:43	stderr	      ^
2024/09/06 18:35:43	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:35:43	stderr	/app/lib/Server.js:311
2024/09/06 18:35:37	stderr	Node.js v20.17.0
2024/09/06 18:35:37	stderr	
2024/09/06 18:35:37	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:37	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:35:37	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:35:37	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:35:37	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:35:37	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:35:37	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:35:37	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:37	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:35:37	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:35:37	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:35:37	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:35:37	stderr	
2024/09/06 18:35:37	stderr	      ^
2024/09/06 18:35:37	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:35:37	stderr	/app/lib/Server.js:311
2024/09/06 18:35:28	stderr	Node.js v20.17.0
2024/09/06 18:35:28	stderr	
2024/09/06 18:35:28	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:28	stderr	    at Object.<anonymous> (/app/server.js:3:1)
2024/09/06 18:35:28	stderr	    at require (node:internal/modules/helpers:179:18)
2024/09/06 18:35:28	stderr	    at Module.require (node:internal/modules/cjs/loader:1311:19)
2024/09/06 18:35:28	stderr	    at Module._load (node:internal/modules/cjs/loader:1104:12)
2024/09/06 18:35:28	stderr	    at Module.load (node:internal/modules/cjs/loader:1288:32)
2024/09/06 18:35:28	stderr	    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024/09/06 18:35:28	stderr	    at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024/09/06 18:35:28	stderr	    at Object.<anonymous> (/app/services/Server.js:5:18)
2024/09/06 18:35:28	stderr	    at new Server (/app/lib/Server.js:311:13)
2024/09/06 18:35:28	stderr	See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
2024/09/06 18:35:28	stderr	Error: DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
2024/09/06 18:35:28	stderr	
2024/09/06 18:35:28	stderr	      ^
2024/09/06 18:35:28	stderr	      throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.\nSee https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
2024/09/06 18:35:28	stderr	/app/lib/Server.js:311
```

**Comment by eandersons** [comment] 2024-09-06 17:53
Duplicate of #1352.

**Comment by snapsl** [comment] 2024-09-07 10:24
Instead of a password hash, wg-easy could use docker secrets.

**Comment by FlavioB79** [comment] 2024-09-07 10:35
Thanks for linking to the original issue thread. I've posted my additional help request there, if you don't mind looking at it and maybe helping me to sort this out... --> https://github.com/wg-easy/wg-easy/issues/1352#issuecomment-2335109783

Thanks!

**Closed** 2024-09-07 16:48 UTC
Labels: type: bug
