### ISSUE TITLE
[Bug]: Clients can't access external network with Debian 12 & rootless podman containers

### ISSUE THREAD

**Issue by obbardc** [wg-easy/wg-easy#1422] opened 2024-09-21 14:55 UTC
### Describe the bug

A client can connect to the wireguard network, but cannot communicate with internal/external devices.

Older version :12 seems to work just fine.

Also same error in docker from docker.io.

### Expected behavior

Work just fine!

### Relevant log output

```shell
podman pod create --name=wg-easy_pod \
  -p=51820:51820/udp \
  -p=8080:51821/tcp

podman run -d --restart=unless-stopped \
  --pod=wg-easy_pod \
  --name=wg-easy \
  --volume=$HOME/containers/wg-easy:/etc/wireguard:Z \
  --cap-add=NET_ADMIN,NET_RAW,SYS_MODULE \
  --cap-drop=MKNOD,AUDIT_WRITE \
  --sysctl=net.ipv4.ip_forward=1 \
  --sysctl=net.ipv4.conf.all.src_valid_mark=1 \
  -e PASSWORD_HASH='hash' \
  -e WG_HOST=host \
  -e WG_DEFAULT_DNS="8.8.8.8, 8.8.4.4" \
  -e WG_ALLOWED_IPS="0.0.0.0/0, ::/0" \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -e WG_PERSISTENT_KEEPALIVE=25 \
  -e WG_DEVICE=ens3 \
  -e WG_DEFAULT_DNS="8.8.8.8, 8.8.4.4" \
  -e WG_ALLOWED_IPS="0.0.0.0/0, ::/0" \
  -e UI_TRAFFIC_STATS=true \
  -e UI_CHART_TYPE=1 \
  ghcr.io/wg-easy/wg-easy:latest
```

**Comment by obbardc** [comment] 2024-09-21 15:09
For reference, devices connected to the VPN can ping each other.

**Comment by mitrios-hub** [comment] 2024-10-15 21:46
are you sure ip_forward is set?

**Comment by mitrios-hub** [comment] 2024-10-15 21:55
when i had same issue i tried:
1. check if really ip_forward is set (sysctl -p)
2. temporary set off firewall (allow all any directions)
3. check postrouting masquerade in nat chain of fw

in most cases reason of the issue is wrong FW settings

i use debian 12 for a long time and wg-easy works fine.

**Comment by kaaax0815** [comment] 2024-10-16 07:17
@obbardc
Stop the container and remove the `WG_DEVICE` env and try again. Maybe this is the problem?

**Comment by obbardc** [comment] 2024-10-16 09:29
So, firstly I checked the `ip_forward` rules in sysctl, seems that podman didn't set them:
```
$ sysctl -a | grep ip_forward
net.ipv4.ip_forward = 0
net.ipv4.ip_forward_update_priority = 1
net.ipv4.ip_forward_use_pmtu = 0

$ sysctl net.ipv4.ip_forward=1 net.ipv4.conf.all.src_valid_mark=1
net.ipv4.ip_forward = 1
net.ipv4.conf.all.src_valid_mark = 1
```

No change.


Cleared out any iptables rules (There was ufw on this server, but uninstalled it):

```
$ iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-sshd (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere 

$ iptables -P INPUT ACCEPT
$ iptables -P FORWARD ACCEPT
$ iptables -P OUTPUT ACCEPT
$ iptables -t nat -F
$ iptables -t mangle -F
$ iptables -F
$ iptables -X
$ ip6tables -P INPUT ACCEPT
$ ip6tables -P FORWARD ACCEPT
$ ip6tables -P OUTPUT ACCEPT
$ ip6tables -t nat -F
$ ip6tables -t mangle -F
$ ip6tables -F
$ ip6tables -X

$ iptables -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
```

Also no change.

**Comment by obbardc** [comment] 2024-10-16 09:29
Also removing `WG_DEVICE` env variable makes no difference.

**Comment by mitrios-hub** [comment] 2024-10-16 09:46
> So, firstly I checked the `ip_forward` rules in sysctl, seems that podman didn't set them:
> 
> ```
> $ iptables -nvL
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> ```
> 
> Also no change.

postrouting masquerade?

**Comment by obbardc** [comment] 2024-10-16 09:54
The output shows:

```
# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain NETAVARK-HOSTPORT-DNAT (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain NETAVARK-HOSTPORT-MASQ (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain NETAVARK-HOSTPORT-SETMARK (0 references)
 pkts bytes target     prot opt in     out     source               destination         
```

Sorry, I am awful with networking :-)

**Comment by mitrios-hub** [comment] 2024-10-16 09:57
my ipt:
```
Chain POSTROUTING (policy ACCEPT 211K packets, 17M bytes)
num   pkts bytes target     prot opt in     out     source               destination
1    5697K 1402M MASQUERADE  0    --  *      !docker0  172.17.0.0/16        0.0.0.0/0
2        0     0 MASQUERADE  0    --  *      !br-61a5fbdf32dc  172.19.0.0/16        0.0.0.0/0
3        0     0 MASQUERADE  6    --  *      *       172.17.0.2           172.17.0.2           tcp dpt:8000
4        0     0 MASQUERADE  6    --  *      *       172.17.0.2           172.17.0.2           tcp dpt:9443
5        0     0 MASQUERADE  17   --  *      *       172.17.0.3           172.17.0.3           udp dpt:51820
6        0     0 MASQUERADE  6    --  *      *       172.17.0.3           172.17.0.3           tcp dpt:51821
```

docker runs iptable rules, try to rebuild wg-easy

**Comment by obbardc** [comment] 2024-10-16 09:58
OK, so I figured out that it works in podman root container mode (creating the pod/container with `sudo`).

Also had to set `WG_DEVICE=tap0` in rootless mode; `WG_DEVICE=eth0` in root mode. So there are definitely some issues when running in rootless mode :-)

**Comment by mitrios-hub** [comment] 2024-10-16 10:01
hm..... it seems there was same issue (using wg devices) some month ago, try to use search.

**Comment by kaaax0815** [comment] 2024-10-16 13:41
Closing as Author resolved the issue

**Closed by kaaax0815** 2024-10-16 13:41 UTC
Labels: type: bug

**Comment by obbardc** [comment] 2024-10-16 13:57
well it's not really resolved, as wg-easy doesnt work when running in rootless podman :-)

**Comment by kaaax0815** [comment] 2024-10-16 14:03
@obbardc Didn't you solve the problem with https://github.com/wg-easy/wg-easy/issues/1422#issuecomment-2416321200?
If yes the issue is related to podman not with `wg-easy` as it expects the interface to be `eth0`
