### ISSUE TITLE
[Bug]: Logging in causes a Javascript error

### ISSUE THREAD

**Issue by spantaleev** [wg-easy/wg-easy#1387] opened 2024-09-10 14:39 UTC
### Describe the bug

This is about version 14.

Supplying an incorrect password on the login form shows an `Unauthorized` alert, as expected.

Logging in with the correct password shows a loading spinner and the following JS error:

> vue.min.js:6 ReferenceError: restoreConfig is not defined
>     at Er.eval (eval at mc (vue.min.js:6:105188), <anonymous>:3:6811)
>     at t._render (vue.min.js:6:45862)
>     at Er.r (vue.min.js:6:79765)
>     at t.get (vue.min.js:6:28262)
>     at t.run (vue.min.js:6:28995)
>     at cn (vue.min.js:6:19867)
>     at Array.<anonymous> (vue.min.js:6:23307)
>     at Sn (vue.min.js:6:22707)

### Expected behavior

No errors after logging in and a functional web UI.

**Comment by moppman** [comment] 2024-09-10 15:11
Sounds like https://github.com/wg-easy/wg-easy/issues/1253#issuecomment-2275076711 (cache issue).

Your browser is probably using a cached version of the client-side code. `restoreConfig` is a new function in `app.js`, which the cached version does not provide.  You should clear the cache for your wg-easy instance and try again.

**Comment by spantaleev** [comment] 2024-09-11 04:47
You're right - doing a full refresh helped!

I'm not sure if you'd like to keep this issue open so that improvements can be made. Perhaps stamping static files with some hash or timestamp would be beneficial:

```html
<script src="./js/app.js"></script>
```

**Comment by kaaax0815** [comment] 2024-09-11 05:25
Closing as duplicate of #1253 
Will be fixed with #1333

**Closed by kaaax0815** 2024-09-11 05:25 UTC
Labels: type: bug
