### ISSUE TITLE
[Feature Request] Persist trafic stats on config file

### ISSUE THREAD

**Issue by TrYkeRm4N** [wg-easy/wg-easy#1037] opened 2024-05-14 17:59 UTC
Hi

I really love your web portal, it's really easy to use and user friendly.

I would ask to request if is it possible to persist on ~/.wg-easy the trafic information so we don't lose it on every reboot of the container.

Thanks in advance, I know you are probably a busy man and you do this for free.

**Comment by eandersons** [comment] 2024-05-14 19:26
This is a duplicate of #1011.

**Closed** 2024-05-14 20:33 UTC
